#!/usr/bin/env bash
# Regenerate sitemap.xml from the live verified-artists list.
#
# Dependencies: curl + jq.
# Reads SUPABASE_ANON_KEY from .env.deploy (same file the FTP deploy uses).
#
# Usage:
#   bash scripts/generate-sitemap.sh          # write over sitemap.xml
#   bash scripts/generate-sitemap.sh --check  # diff against existing, exit 1 if stale
#
# Hook this into your deploy pipeline (or run weekly) so newly-verified
# artists get into the sitemap within a refresh window.

set -euo pipefail

SUPABASE_URL="https://vgjmfpryobsuboukbemr.supabase.co"
SITE_URL="https://rosterplus.io"
OUT="$(dirname "$0")/../sitemap.xml"

# The anon key is already public in assets/js/app.js (it's safe to expose
# by design — RLS enforces row-level access). Extract it rather than
# duplicating it in a second env file.
APP_JS="$(dirname "$0")/../assets/js/app.js"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-$(grep -oE "SUPABASE_ANON_KEY = '[^']+'" "$APP_JS" | head -1 | sed -E "s/^.*= '(.+)'$/\1/")}"

if [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "error: could not extract SUPABASE_ANON_KEY from $APP_JS" >&2
  exit 1
fi

TODAY="$(date -u +%Y-%m-%d)"

# Pull verified artists. Using the REST endpoint so we don't need service-role
# privilege — the anon key + public.artists RLS is enough for public rows.
artists_json="$(curl -sSf \
  -H "apikey: $SUPABASE_ANON_KEY" \
  -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
  "$SUPABASE_URL/rest/v1/artists?select=id,updated_at&verified=eq.true&order=stage_name.asc")"

artist_count="$(echo "$artists_json" | jq 'length')"
echo "Found $artist_count verified artists."

# Build sitemap body
{
  cat <<HEADER
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Sitemap for rosterplus.io
  Last regenerated: $TODAY
  Regenerated by: scripts/generate-sitemap.sh
  Artist count: $artist_count
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  <!-- Marketing + public surfaces -->
  <url>
    <loc>$SITE_URL/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
    <lastmod>$TODAY</lastmod>
  </url>
  <url>
    <loc>$SITE_URL/directory.html</loc>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
    <lastmod>$TODAY</lastmod>
  </url>
  <url>
    <loc>$SITE_URL/auth.html</loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>$SITE_URL/privacy.html</loc>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>$SITE_URL/terms.html</loc>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>$SITE_URL/status.html</loc>
    <changefreq>hourly</changefreq>
    <priority>0.4</priority>
  </url>

  <!-- Verified artist profiles — auto-generated. -->
HEADER

  echo "$artists_json" | jq -r --arg site "$SITE_URL" '
    .[] |
    "  <url>\n    <loc>\($site)/profile.html?id=\(.id)</loc>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n    <lastmod>\(.updated_at | split("T")[0])</lastmod>\n  </url>"
  '

  echo "</urlset>"
} > "$OUT.tmp"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$OUT" "$OUT.tmp" >/dev/null 2>&1; then
    echo "sitemap.xml is stale. Run this script without --check to regenerate."
    rm -f "$OUT.tmp"
    exit 1
  fi
  rm -f "$OUT.tmp"
  echo "sitemap.xml is up to date."
  exit 0
fi

mv "$OUT.tmp" "$OUT"
echo "Wrote $OUT ($artist_count artist entries)."
